# Static Datasource Configuration
# YAML Example

records:
  - name: site-a.example.com
    metadata:
      labels:
        region: seoul
        foo: bar
  - name: site-b.example.com
    metadata:
      labels:
        region: usa
        foo: bar3
